import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavbarComp from './Components/Navbar/Navbar'
import SidebarComp from './Components/Sidebar/Sidebar'
import FooterComp from './Components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarComp />
        <div className="main-wrapper">

          <div className="side">
          <SidebarComp />
          </div>
          <div className="matches-feed">
         
          {children}
          </div>
        </div>


        <FooterComp />

      </body>
    </html>
  )
}
